name: Code Quality

on: [push]

jobs:
  Code-Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Audit
        run: npm audit
      - name: CI
        run: npm ci
      - name: Type Check
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Prettier
        run: npm run prettier:check
