name: Publish Dev Staging
on:
  push: 
    branches: 
      - develop
env: 
  REPO_NAME: zarf-website-staging

jobs:
  deploy-staging:
    environment:
      name: development
      url: https://${{ github.repository_owner }}.github.io/${{ env.REPO_NAME }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2
        env: 
          PATH_PREFIX: /${{ env.REPO_NAME }}
        with: 
          deploy-branch: main
          deploy-repo: ${{ env.REPO_NAME }}
          access-token: ${{ secrets.ACCESS_TOKEN }}
          gatsby-args: --prefix-paths